version: '3.8'  

services:
  
  mysql:

    container_name: ${NAME_CONTAINER_DB}

    image: ${IMAGE_BD}
    
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PORT_DB}:${PORT_DB}"
    expose:
      - ${PORT_DB}
    networks:
      - base_network
    volumes:
      - my_db:/var/lib/mysql

  backend-app:
    container_name: ${NAME_NODE_CONTAINER}  
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      - PORT= ${PORT}
      - APP_URL= ${APP_URL}  
      - DATABASE_URL = ${DATABASE_URL}
    ports:
      - "${PORT}:${PORT}"  
    networks:
      - base_network
    command: npm start

    depends_on: 
      - mysql

networks:
  base_network:
    driver: bridge

volumes:
  my_db: